name: 't2gp build info'
description: 'get build information'
inputs:
  labels:
    description: pull request labels, for push , it is empty array
    required: true,
    default: '[]'
  available_sandboxes:
    description: available sandboxes
    required: true
    default: 'sandbox1,sandbox2,sandbox3'
  master_environment_name:
    description: master branch default environment name
    required: true
    default: 'T2gpWebDocker-env'
  environment_prefix:
    description: prefix for the environment name
    required: true
    default: ''
  develop_environment_name:
    description: develop branch default environment name
    required: true
    default: 'd2c-beanstalk-infra-dev'
  release_environment_name:
    description: release environment name
    required: true
    default: 'd2c-beanstalk-infra-dev'
  url_mappings:
    description: environment name to url url_mappings
    required: false
    default: '{}'
  branch_name_max:
    description: maximum length of sanitized branch name
    required: true
    default: 63
outputs:
  environment_name:
    description: beanstalk environment name
  branch_name:
    description: branch name
  version:
    description: git commit short hash
  url:
    description: the deploy url
  package_version:
    description: the version from package.json

runs:
  using: 'node12'
  main: '.dist/index.js'
