name: 't2gp build info'
description: 'get build information'
inputs:
  labels:
    description: pull request labels, for push , it is empty array
    required: true
  available_sandboxes:
    description: avaiable sandboxes
    required: true
    default: 'sandbox1,sandbox2,sandbox3'
  master_environment_name:
    description: master branch default environment name
    required: true
    default: 'T2gpWebDocker-env'
  url_mappings:
    description: environment name to url url_mappings
    required: false
    default: '{}'
outputs:
  environment_name:
    description: beanstalk environment name
  branch_name:
    description: branch name
  version:
    description: git commit short hash
  url:
    description: the depoloy url

runs:
  using: 'node12'
  main: '.dist/index.js'
