name: d2c actions

on: [push, pull_request]

jobs:
  test:
    name: test build info
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: build buildinfo action
        working-directory: buildinfo
        run: |
          npm install
          npm run build
      - name: test buildinfo action
        id: buildinfo
        uses: "./buildinfo"
        with:
          labels: "${{ toJson(github.event.pull_request.labels.*.name) }}"
      - name: use output values
        run: |
          echo ${{steps.buildinfo.outputs.environment_name}}
          echo ${{steps.buildinfo.outputs.version}}
          echo ${{steps.buildinfo.outputs.branch_name}}
