name: d2c actions

on: [pull_request]

jobs:
  test:
    name: test build info
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: build buildinfo action
        run: |
          npm install
          npm run build
      - name: test buildinfo action
        id: buildinfo
        uses: './'
        with:
          labels: '${{ toJson(github.event.pull_request.labels.*.name) }}'
          environment_prefix: 'd2c-beanstalk-infra-'
          develop_environment_name: 'eb-develop'
          url_mappings: |
            {
              "sandbox1": "http://sb1.d2dragon.net",
              "sandbox2": "http://sb2.d2dragon.net",
              "T2gpWebDocker-env": "http://dev.d2dragon.net"
            }
      - name: use output values
        run: |
          echo ${{github.sha}}
          echo ${{steps.buildinfo.outputs.environment_name}}
          echo ${{steps.buildinfo.outputs.version}}
          echo ${{steps.buildinfo.outputs.branch_name}}
          echo ${{steps.buildinfo.outputs.url}}
          echo ${{steps.buildinfo.outputs.package_version}}
